### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by neomaximus2k** [digitorus/eramba#4]
Did a pull, docker-compose up -d and got the following:

ERamba Test> docker-compose up -d
Pulling db (digitorus/eramba-db:latest)...
Traceback (most recent call last):
  File "site-packages\dockerpycreds\store.py", line 52, in _execute
  File "subprocess.py", line 336, in check_output
  File "subprocess.py", line 403, in run
  File "subprocess.py", line 709, in __init__
  File "subprocess.py", line 997, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\docker\auth.py", line 126, in _resolve_authconfig_credstore
  File "site-packages\dockerpycreds\store.py", line 25, in get
  File "site-packages\dockerpycreds\store.py", line 70, in _execute
dockerpycreds.errors.StoreError: docker-credential-desktop not installed or not available in PATH

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 127, in perform_command
  File "compose\cli\main.py", line 1039, in up
  File "compose\cli\main.py", line 1035, in up
  File "compose\project.py", line 465, in up
  File "compose\service.py", line 321, in ensure_image_exists
  File "compose\service.py", line 1105, in pull
  File "site-packages\docker\api\image.py", line 359, in pull
  File "site-packages\docker\auth.py", line 47, in get_config_header
  File "site-packages\docker\auth.py", line 94, in resolve_authconfig
  File "site-packages\docker\auth.py", line 143, in _resolve_authconfig_credstore
docker.errors.DockerException: Credentials store error: StoreError('docker-credential-desktop not installed or not available in PATH',)
[23824] Failed to execute script docker-compose
ERamba Test>

**Comment by vanbroup** [comment]
This issue doesn't look to be related to this repository but your local setup:

```sh
dockerpycreds.errors.StoreError: docker-credential-desktop not installed or not available in PATH
```
